branch-defaults:
  AWS:
    environment: SchematicCaptureBe-env
environment-defaults:
  SchematicCaptureBe-env:
    branch: AWS
    repository: origin
global:
  application_name: schematic-capture-be
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.14.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
